import { useImperativeHandle, useMemo, useState, useEffect } from "react";
import { X, Calendar as CalendarIcon } from "lucide-react";
import { CONTROL_INPUT, ERROR_PANEL, FIELD_LABEL } from "@/lib/styles";
import type { Batch } from "@my-inventory-app/shared";
import { createInventoryMovement } from "@/services/inventoryMovementService";
import { createBatch, getBatchesByVariantId } from "@/services/batchService";
import { getProductById } from "@/services/productService";
import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { addYears, format, subDays } from "date-fns";
import type { DisplayInventoryRow } from "@/components/inventory/InventoryTable";

const NEW_BATCH_VALUE = "__new__";
const DEFAULT_LOCATION_ID = 1;
const DEFAULT_LOCATION_NAME = "晁欣";

export interface InventoryMovementHandle {
    submit: () => Promise<void>;
}

interface InventoryMovementProps {
    items: DisplayInventoryRow[];
    initialVariantId?: number | null;
    onSavingChange?: (isSaving: boolean) => void;
    onSuccess: () => void;
    ref?: React.Ref<InventoryMovementHandle>;
}

interface AdjustmentDraftRow {
    variantId: number;
    targetQuantity?: string;
    batchId?: number | "new";
    newBatchNumber?: string;
    batchNameAutoGenerated?: boolean;
    expirationDate?: Date;
}

const roundQuantity = (value: number): number => Math.round(value * 1e6) / 1e6;
const getDefaultBatchNumber = (expirationDate?: Date): string =>
    `${format(new Date(), "yyyy/MM/dd")} - ${expirationDate ? format(expirationDate, "yyyy/MM/dd") : "未設定"}`;
const getDefaultBatchExpirationDate = (): Date =>
    subDays(addYears(new Date(), 2), 1);

export const InventoryMovement = ({
    items,
    initialVariantId,
    onSavingChange,
    onSuccess,
    ref,
}: InventoryMovementProps) => {
    const [locationId] = useState<number>(DEFAULT_LOCATION_ID);
    const [rows, setRows] = useState<AdjustmentDraftRow[]>(() =>
        initialVariantId != null
            ? [{ variantId: initialVariantId, targetQuantity: undefined }]
            : []
    );
    const [reason, setReason] = useState("");
    const [adjustmentDate, setAdjustmentDate] = useState<Date | undefined>(() => new Date());
    const [adjustmentCalendarOpen, setAdjustmentCalendarOpen] = useState(false);
    const [formError, setFormError] = useState<string | null>(null);

    // Fast O(1) item lookup
    const itemMap = useMemo(() => {
        const map = new Map<number, DisplayInventoryRow>();
        for (const item of items) {
            map.set(item.variantId, item);
        }
        return map;
    }, [items]);

    // Metadata caches (record lookup without dependency loops)
    const [batchTrackedMap, setBatchTrackedMap] = useState<Record<number, boolean>>({});
    const [batchesByVariant, setBatchesByVariant] = useState<Record<number, Batch[]>>({});

    // Fetch batch tracked status and existing batches safely
    useEffect(() => {
        let isMounted = true;

        const loadMetadata = async () => {
            for (const row of rows) {
                const item = itemMap.get(row.variantId);
                if (!item) continue;

                // 1. Check parent product batch tracking
                let isBatchTracked = batchTrackedMap[row.variantId];
                if (isBatchTracked === undefined) {
                    try {
                        const product = await getProductById(item.productId);
                        isBatchTracked = product.batchTracked;
                        if (isMounted) {
                            setBatchTrackedMap((prev) => ({
                                ...prev,
                                [row.variantId]: product.batchTracked,
                            }));
                        }
                    } catch {
                        isBatchTracked = false;
                    }
                }

                // 2. Fetch existing batches if product is batch tracked
                if (isBatchTracked && batchesByVariant[row.variantId] === undefined) {
                    try {
                        const batches = await getBatchesByVariantId(row.variantId);
                        if (isMounted) {
                            setBatchesByVariant((prev) => ({
                                ...prev,
                                [row.variantId]: batches,
                            }));
                        }
                    } catch {
                        if (isMounted) {
                            setBatchesByVariant((prev) => ({
                                ...prev,
                                [row.variantId]: [],
                            }));
                        }
                    }
                }
            }
        };

        loadMetadata();

        return () => {
            isMounted = false;
        };
    }, [rows, itemMap]); // <-- Clean dependency array: no self-triggering state

    const selectableVariants = useMemo(() => {
        const alreadyAdded = new Set(rows.map((row) => row.variantId));

        return items
            .filter((item) => !alreadyAdded.has(item.variantId))
            .map((item) => ({
                variantId: item.variantId,
                label: item.displayName,
            }))
            .sort((a, b) => a.label.localeCompare(b.label));
    }, [items, rows]);

    const handleAddRow = (variantId: number) => {
        setFormError(null);
        setRows((prev) => [...prev, { variantId, targetQuantity: undefined }]);
    };

    const handleRemoveRow = (variantId: number) => {
        setRows((prev) => prev.filter((row) => row.variantId !== variantId));
    };

    const handleTargetChange = (variantId: number, targetQuantity: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => (row.variantId === variantId ? { ...row, targetQuantity } : row))
        );
    };

    const handleBatchChange = (variantId: number, value: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.variantId !== variantId) return row;

                if (value === "") {
                    return {
                        ...row,
                        batchId: undefined,
                        newBatchNumber: undefined,
                        batchNameAutoGenerated: undefined,
                        expirationDate: undefined,
                    };
                }
                if (value === NEW_BATCH_VALUE) {
                    const defaultExp = getDefaultBatchExpirationDate();
                    return {
                        ...row,
                        batchId: "new",
                        expirationDate: defaultExp,
                        newBatchNumber: getDefaultBatchNumber(defaultExp),
                        batchNameAutoGenerated: true,
                    };
                }
                return {
                    ...row,
                    batchId: Number(value),
                    newBatchNumber: undefined,
                    batchNameAutoGenerated: undefined,
                    expirationDate: undefined,
                };
            })
        );
    };

    const handleNewBatchNumberChange = (variantId: number, newBatchNumber: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) =>
                row.variantId === variantId
                    ? { ...row, newBatchNumber, batchNameAutoGenerated: false }
                    : row
            )
        );
    };

    const handleAdjustmentDateSelect = (date: Date | undefined) => {
        setAdjustmentDate(date);
        setAdjustmentCalendarOpen(false);
    };

    const handleExpirationDateChange = (variantId: number, date: Date | undefined) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.variantId !== variantId) return row;
                return {
                    ...row,
                    expirationDate: date,
                    ...(row.batchNameAutoGenerated && {
                        newBatchNumber: getDefaultBatchNumber(date),
                    }),
                };
            })
        );
    };

    const getEffectiveQuantityString = (row: AdjustmentDraftRow): string => {
        if (row.targetQuantity !== undefined) return row.targetQuantity;
        const currentStock = itemMap.get(row.variantId)?.inStock ?? 0;
        return String(currentStock);
    };

    const deltaFor = (row: AdjustmentDraftRow): number | null => {
        const rawStr = getEffectiveQuantityString(row);
        if (rawStr.trim() === "") return null;

        const target = Number(rawStr);
        if (Number.isNaN(target)) return null;

        const currentStock = itemMap.get(row.variantId)?.inStock ?? 0;
        return roundQuantity(target - currentStock);
    };

    const handleSave = async () => {
        if (rows.length === 0) {
            setFormError("請至少新增一個調整項目。");
            return;
        }

        const pendingOperations: Array<{
            variantId: number;
            delta: number;
            batchId: number | null;
            newBatchDraft?: { number: string; expiredAt: string };
        }> = [];

        for (const row of rows) {
            const rawStr = getEffectiveQuantityString(row);
            if (rawStr.trim() === "") continue;

            const target = Number(rawStr);
            if (Number.isNaN(target)) {
                setFormError("調整後數量必須是數字。");
                return;
            }
            if (target < 0) {
                setFormError("調整後數量不可小於 0。");
                return;
            }

            const currentStock = itemMap.get(row.variantId)?.inStock ?? 0;
            const delta = roundQuantity(target - currentStock);
            if (delta === 0) continue;

            const isBatchTracked = batchTrackedMap[row.variantId] ?? false;

            if (isBatchTracked) {
                if (!row.batchId) {
                    setFormError(`請為批次追蹤商品設定批次。`);
                    return;
                }

                if (row.batchId === "new") {
                    const trimmedBatchNum = row.newBatchNumber?.trim();
                    if (!trimmedBatchNum) {
                        setFormError("請輸入新批次編號。");
                        return;
                    }
                    if (!row.expirationDate) {
                        setFormError("請選擇新批次的有效日期。");
                        return;
                    }

                    pendingOperations.push({
                        variantId: row.variantId,
                        delta,
                        batchId: null,
                        newBatchDraft: {
                            number: trimmedBatchNum,
                            expiredAt: row.expirationDate.toISOString(),
                        },
                    });
                } else {
                    pendingOperations.push({
                        variantId: row.variantId,
                        delta,
                        batchId: row.batchId,
                    });
                }
            } else {
                pendingOperations.push({
                    variantId: row.variantId,
                    delta,
                    batchId: null,
                });
            }
        }

        if (pendingOperations.length === 0) {
            setFormError("沒有任何數量變動。");
            return;
        }

        setFormError(null);
        onSavingChange?.(true);

        try {
            for (const op of pendingOperations) {
                let resolvedBatchId = op.batchId;

                // 1. Create batch first if new
                if (op.newBatchDraft) {
                    const createdBatch = await createBatch({
                        variantId: op.variantId,
                        batchNumber: op.newBatchDraft.number,
                        quantity: Math.max(op.delta, 0),
                        expiredAt: op.newBatchDraft.expiredAt,
                    });
                    resolvedBatchId = createdBatch.id;
                }

                // 2. Post ledger movement
                await createInventoryMovement({
                    variantId: op.variantId,
                    batchId: resolvedBatchId,
                    quantityAdjusted: op.delta,
                    locationId,
                    referenceType: "ADJUSTMENT",
                    referenceId: reason.trim() ? reason.trim() : null,
                });
            }

            onSuccess();
        } catch (err: unknown) {
            setFormError(err instanceof Error ? err.message : "庫存調整失敗。");
        } finally {
            onSavingChange?.(false);
        }
    };

    useImperativeHandle(ref, () => ({ submit: handleSave }));

    return (
        <div className="flex flex-col gap-y-5">
            {formError && <div className={ERROR_PANEL}>{formError}</div>}

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>倉庫</label>
                    <input
                        type="text"
                        className={`${CONTROL_INPUT} bg-muted text-muted-foreground cursor-not-allowed`}
                        value={DEFAULT_LOCATION_NAME}
                        disabled
                    />
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>調整日期</label>
                    <Popover open={adjustmentCalendarOpen} onOpenChange={setAdjustmentCalendarOpen}>
                        <PopoverTrigger
                            render={
                                <Button
                                    variant="outline"
                                    className="w-full justify-start text-left font-normal bg-background border border-input text-foreground hover:bg-muted"
                                >
                                    <CalendarIcon className="mr-2 h-4 w-4 text-slate-400" />
                                    {adjustmentDate ? format(adjustmentDate, "yyyy/MM/dd") : <span>選擇日期</span>}
                                </Button>
                            }
                        />
                        <PopoverContent className="w-auto p-0 bg-popover border-border text-popover-foreground" align="start">
                            <Calendar
                                mode="single"
                                selected={adjustmentDate}
                                onSelect={handleAdjustmentDateSelect}
                            />
                        </PopoverContent>
                    </Popover>
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>原因 (選填)</label>
                    <input
                        type="text"
                        className={CONTROL_INPUT}
                        placeholder="例如: 盤點差異、耗損"
                        value={reason}
                        onChange={(e) => setReason(e.target.value)}
                    />
                </div>
            </div>

            <div className="rounded-lg border border-border overflow-hidden">
                <table className="w-full text-left text-sm text-foreground">
                    <thead className="bg-muted text-muted-foreground font-medium text-xs uppercase tracking-wider">
                        <tr>
                            <th className="py-3 px-4 border-b border-border">商品 / 規格</th>
                            <th className="py-3 px-4 border-b border-border text-right">目前庫存</th>
                            <th className="py-3 px-4 border-b border-border text-right">調整後數量</th>
                            <th className="py-3 px-4 border-b border-border">批次與有效日期</th>
                            <th className="py-3 px-4 border-b border-border text-right">變動</th>
                            <th className="py-3 px-4 border-b border-border w-10" />
                        </tr>
                    </thead>
                    <tbody className="font-mono text-xs">
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={6} className="py-8 text-center text-muted-foreground font-sans">
                                    請在下方新增要調整的商品。
                                </td>
                            </tr>
                        ) : (
                            rows.map((row) => {
                                const item = itemMap.get(row.variantId);
                                const isBatchTracked = batchTrackedMap[row.variantId] ?? false;
                                const current = item?.inStock ?? 0;
                                const effectiveQtyStr = getEffectiveQuantityString(row);
                                const delta = deltaFor(row);
                                const variantBatches = batchesByVariant[row.variantId] ?? [];

                                return (
                                    <tr key={row.variantId} className="border-b border-border/40">
                                        <td className="py-2.5 px-4 font-sans">
                                            <div className="font-medium text-foreground">
                                                {item?.productName ?? `款式 #${row.variantId}`}
                                            </div>
                                            {item?.configValues && item.configValues.length > 0 && (
                                                <div className="text-xs text-muted-foreground mt-0.5">
                                                    {item.configValues.join(" / ")}
                                                </div>
                                            )}
                                        </td>
                                        <td className="py-2.5 px-4 text-right text-muted-foreground">
                                            {current}
                                        </td>
                                        <td className="py-2.5 px-4 text-right">
                                            <input
                                                type="number"
                                                step="any"
                                                min="0"
                                                className="w-28 text-right bg-background border border-input focus:border-ring rounded px-2 py-1 text-foreground focus:outline-none transition"
                                                value={effectiveQtyStr}
                                                onChange={(e) =>
                                                    handleTargetChange(row.variantId, e.target.value)
                                                }
                                            />
                                        </td>
                                        <td className="py-2.5 px-4 gap-x-3">
                                            {isBatchTracked ? (
                                                <div className="flex gap-x-3 items-center w-full">
                                                    <div className="flex flex-col gap-y-1 w-full">
                                                        <select
                                                            className="bg-background border border-input focus:border-ring rounded px-2 py-1 text-foreground focus:outline-none focus:ring-2 focus:ring-ring/30 transition text-xs"
                                                            value={
                                                                row.batchId === "new"
                                                                    ? NEW_BATCH_VALUE
                                                                    : row.batchId ?? ""
                                                            }
                                                            onChange={(e) =>
                                                                handleBatchChange(row.variantId, e.target.value)
                                                            }
                                                        >
                                                            <option value="">選擇批次...</option>
                                                            {variantBatches.map((b) => (
                                                                <option key={b.id} value={b.id}>
                                                                    {b.batchNumber}
                                                                </option>
                                                            ))}
                                                            <option value={NEW_BATCH_VALUE}>+ 新增批次...</option>
                                                        </select>
                                                        {row.batchId === "new" && (
                                                            <input
                                                                type="text"
                                                                placeholder="新批次編號"
                                                                className="bg-background border border-input focus:border-ring rounded px-2 py-1 text-foreground focus:outline-none focus:ring-2 focus:ring-ring/30 transition text-xs"
                                                                value={row.newBatchNumber ?? ""}
                                                                onChange={(e) =>
                                                                    handleNewBatchNumberChange(
                                                                        row.variantId,
                                                                        e.target.value
                                                                    )
                                                                }
                                                            />
                                                        )}
                                                    </div>

                                                    {row.batchId === "new" && (
                                                        <div>
                                                            <Popover>
                                                                <PopoverTrigger
                                                                    render={
                                                                        <Button
                                                                            variant="outline"
                                                                            size="sm"
                                                                            className="bg-background border-input text-foreground hover:bg-muted text-xs px-2.5"
                                                                        >
                                                                            <CalendarIcon className="h-3.5 w-3.5 mr-1 text-muted-foreground" />
                                                                            {row.expirationDate
                                                                                ? format(row.expirationDate, "yyyy/MM/dd")
                                                                                : "有效日期"}
                                                                        </Button>
                                                                    }
                                                                />
                                                                <PopoverContent className="w-auto p-0 bg-popover border-border text-popover-foreground" align="start">
                                                                    <Calendar
                                                                        mode="single"
                                                                        selected={row.expirationDate}
                                                                        onSelect={(date) => handleExpirationDateChange(row.variantId, date)}
                                                                    />
                                                                </PopoverContent>
                                                            </Popover>
                                                        </div>
                                                    )}
                                                </div>
                                            ) : (
                                                <span className="text-muted-foreground">—</span>
                                            )}
                                        </td>
                                        <td
                                            className={`py-2.5 px-4 text-right font-medium ${delta === null || delta === 0
                                                    ? "text-muted-foreground"
                                                    : delta > 0
                                                        ? "text-emerald-400"
                                                        : "text-amber-400"
                                                }`}
                                        >
                                            {delta === null ? "—" : delta > 0 ? `+${delta}` : delta}
                                        </td>
                                        <td className="py-2.5 px-4 text-right">
                                            <button
                                                type="button"
                                                onClick={() => handleRemoveRow(row.variantId)}
                                                className="text-muted-foreground hover:text-destructive p-1 transition-colors"
                                                title="移除"
                                            >
                                                <X className="w-4 h-4" />
                                            </button>
                                        </td>
                                    </tr>
                                );
                            })
                        )}
                    </tbody>
                </table>
            </div>

            <div className="flex flex-col gap-y-1">
                <label className={FIELD_LABEL}>新增商品</label>
                <select
                    className={CONTROL_INPUT}
                    value=""
                    onChange={(e) => {
                        if (e.target.value) handleAddRow(Number(e.target.value));
                    }}
                >
                    <option value="">選擇要調整的商品...</option>
                    {selectableVariants.map((variant) => (
                        <option key={variant.variantId} value={variant.variantId}>
                            {variant.label}
                        </option>
                    ))}
                </select>
            </div>
        </div>
    );
};