// src/components/inventory/InventoryMovement.tsx
import { useImperativeHandle, useMemo, useState, useEffect, type Ref } from "react";
import { X, Calendar as CalendarIcon } from "lucide-react";
import { CONTROL_INPUT, ERROR_PANEL, FIELD_LABEL } from "@/lib/styles";
import type { Batch } from "@my-inventory-app/shared";
import { createInventoryMovement } from "@/services/inventoryMovementService";
import { createBatch, getBatchesByVariantId, updateBatch } from "@/services/batchService";
import { getProductById } from "@/services/productService";
import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { InlineInput } from "@/components/InlineInput";
import { addYears, format, subDays } from "date-fns";
import type { DisplayInventoryRow } from "@/components/inventory/InventoryTable";

const NEW_BATCH_VALUE = "__new__";
const DEFAULT_LOCATION_ID = 1;
const DEFAULT_LOCATION_NAME = "晁欣";

export interface InventoryMovementHandle {
    submit: () => Promise<void>;
}

interface InventoryMovementProps {
    items: DisplayInventoryRow[];
    initialVariantId?: number | null;
    onSavingChange?: (isSaving: boolean) => void;
    onSuccess: () => void;
    ref?: Ref<InventoryMovementHandle>;
}

interface AdjustmentDraftRow {
    rowId: string;
    variantId: number;
    targetQuantity?: number;
    batchId?: number | "new";
    newBatchNumber?: string;
    batchNameAutoGenerated?: boolean;
    expirationDate?: Date;
}

const roundQuantity = (value: number): number => Math.round(value * 1e6) / 1e6;
const getDefaultBatchNumber = (expirationDate?: Date): string =>
    `${format(new Date(), "yyyy/MM/dd")} - ${expirationDate ? format(expirationDate, "yyyy/MM/dd") : "未設定"}`;
const getDefaultBatchExpirationDate = (): Date =>
    subDays(addYears(new Date(), 2), 1);

export const InventoryMovement = ({
    items,
    initialVariantId,
    onSavingChange,
    onSuccess,
    ref,
}: InventoryMovementProps) => {
    const [locationId] = useState<number>(DEFAULT_LOCATION_ID);
    const [rows, setRows] = useState<AdjustmentDraftRow[]>(() =>
        initialVariantId != null
            ? [{ rowId: `row-${Date.now()}-0`, variantId: initialVariantId, targetQuantity: undefined }]
            : []
    );
    const [reason, setReason] = useState("");
    const [adjustmentDate, setAdjustmentDate] = useState<Date | undefined>(() => new Date());
    const [adjustmentCalendarOpen, setAdjustmentCalendarOpen] = useState(false);
    const [formError, setFormError] = useState<string | null>(null);

    const itemMap = useMemo(() => {
        const map = new Map<number, DisplayInventoryRow>();
        for (const item of items) {
            map.set(item.variantId, item);
        }
        return map;
    }, [items]);

    const [batchTrackedMap, setBatchTrackedMap] = useState<Record<number, boolean>>({});
    const [batchesByVariant, setBatchesByVariant] = useState<Record<number, Batch[]>>({});

    useEffect(() => {
        let isMounted = true;

        const loadMetadata = async () => {
            for (const row of rows) {
                const item = itemMap.get(row.variantId);
                if (!item) continue;

                let isBatchTracked = batchTrackedMap[row.variantId];
                if (isBatchTracked === undefined) {
                    try {
                        const product = await getProductById(item.productId);
                        isBatchTracked = product.batchTracked;
                        if (isMounted) {
                            setBatchTrackedMap((prev) => ({
                                ...prev,
                                [row.variantId]: product.batchTracked,
                            }));
                        }
                    } catch {
                        isBatchTracked = false;
                    }
                }

                if (isBatchTracked && batchesByVariant[row.variantId] === undefined) {
                    try {
                        const batches = await getBatchesByVariantId(row.variantId);
                        if (isMounted) {
                            setBatchesByVariant((prev) => ({
                                ...prev,
                                [row.variantId]: batches,
                            }));
                        }
                    } catch {
                        if (isMounted) {
                            setBatchesByVariant((prev) => ({
                                ...prev,
                                [row.variantId]: [],
                            }));
                        }
                    }
                }
            }
        };

        loadMetadata();

        return () => {
            isMounted = false;
        };
    }, [rows, itemMap]);

    const selectableVariants = useMemo(() => {
        return items
            .map((item) => ({
                variantId: item.variantId,
                label: item.displayName,
            }))
            .sort((a, b) => a.label.localeCompare(b.label));
    }, [items]);

    const handleAddRow = (variantId: number) => {
        setFormError(null);
        setRows((prev) => [
            ...prev,
            { rowId: `row-${Date.now()}-${prev.length}`, variantId, targetQuantity: undefined },
        ]);
    };

    const handleRemoveRow = (rowId: string) => {
        setRows((prev) => prev.filter((row) => row.rowId !== rowId));
    };

    const handleTargetChange = (rowId: string, targetQuantity: number) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => (row.rowId === rowId ? { ...row, targetQuantity } : row))
        );
    };

    const handleBatchChange = (rowId: string, value: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.rowId !== rowId) return row;

                if (value === "") {
                    return {
                        ...row,
                        batchId: undefined,
                        newBatchNumber: undefined,
                        batchNameAutoGenerated: undefined,
                        expirationDate: undefined,
                        targetQuantity: undefined,
                    };
                }
                if (value === NEW_BATCH_VALUE) {
                    const defaultExp = getDefaultBatchExpirationDate();
                    return {
                        ...row,
                        batchId: "new",
                        expirationDate: defaultExp,
                        newBatchNumber: getDefaultBatchNumber(defaultExp),
                        batchNameAutoGenerated: true,
                        targetQuantity: 0,
                    };
                }

                const batchIdNum = Number(value);
                const batches = batchesByVariant[row.variantId] ?? [];
                const matchedBatch = batches.find((b) => b.id === batchIdNum);

                return {
                    ...row,
                    batchId: batchIdNum,
                    newBatchNumber: undefined,
                    batchNameAutoGenerated: undefined,
                    expirationDate: undefined,
                    targetQuantity: matchedBatch ? matchedBatch.quantity : 0,
                };
            })
        );
    };

    const handleNewBatchNumberChange = (rowId: string, newBatchNumber: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) =>
                row.rowId === rowId
                    ? { ...row, newBatchNumber, batchNameAutoGenerated: false }
                    : row
            )
        );
    };

    const handleExpirationDateChange = (rowId: string, date: Date | undefined) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.rowId !== rowId) return row;
                return {
                    ...row,
                    expirationDate: date,
                    ...(row.batchNameAutoGenerated && {
                        newBatchNumber: getDefaultBatchNumber(date),
                    }),
                };
            })
        );
    };

    const getCurrentStock = (row: AdjustmentDraftRow): number => {
        const isBatchTracked = batchTrackedMap[row.variantId] ?? false;
        if (!isBatchTracked) {
            return itemMap.get(row.variantId)?.inStock ?? 0;
        }

        if (row.batchId === "new") return 0;
        if (typeof row.batchId === "number") {
            const batches = batchesByVariant[row.variantId] ?? [];
            const found = batches.find((b) => b.id === row.batchId);
            return found ? found.quantity : 0;
        }

        return 0;
    };

    const getEffectiveQuantity = (row: AdjustmentDraftRow): number => {
        if (row.targetQuantity !== undefined) return row.targetQuantity;
        return getCurrentStock(row);
    };

    const deltaFor = (row: AdjustmentDraftRow): number | null => {
        const target = getEffectiveQuantity(row);
        if (Number.isNaN(target)) return null;

        const currentStock = getCurrentStock(row);
        return roundQuantity(target - currentStock);
    };

    const handleSave = async () => {
        if (rows.length === 0) {
            setFormError("請至少新增一個調整項目。");
            return;
        }

        const pendingOperations: Array<{
            variantId: number;
            delta: number;
            targetQuantity: number;
            batchId: number | null;
            newBatchDraft?: { number: string; expiredAt: string };
        }> = [];

        for (const row of rows) {
            const target = getEffectiveQuantity(row);
            if (Number.isNaN(target)) {
                setFormError("調整後數量必須是數字。");
                return;
            }
            if (target < 0) {
                setFormError("調整後數量不可小於 0。");
                return;
            }

            const currentStock = getCurrentStock(row);
            const delta = roundQuantity(target - currentStock);
            if (delta === 0) continue;

            const isBatchTracked = batchTrackedMap[row.variantId] ?? false;

            if (isBatchTracked) {
                if (!row.batchId) {
                    const item = itemMap.get(row.variantId);
                    setFormError(`「${item?.productName || "商品"}」為批次追蹤品項，請指定批次。`);
                    return;
                }

                if (row.batchId === "new") {
                    const trimmedBatchNum = row.newBatchNumber?.trim();
                    if (!trimmedBatchNum) {
                        setFormError("請輸入新批次編號。");
                        return;
                    }
                    if (!row.expirationDate) {
                        setFormError("請選擇新批次的有效日期。");
                        return;
                    }

                    pendingOperations.push({
                        variantId: row.variantId,
                        delta,
                        targetQuantity: target,
                        batchId: null,
                        newBatchDraft: {
                            number: trimmedBatchNum,
                            expiredAt: row.expirationDate.toISOString(),
                        },
                    });
                } else {
                    pendingOperations.push({
                        variantId: row.variantId,
                        delta,
                        targetQuantity: target,
                        batchId: row.batchId,
                    });
                }
            } else {
                pendingOperations.push({
                    variantId: row.variantId,
                    delta,
                    targetQuantity: target,
                    batchId: null,
                });
            }
        }

        if (pendingOperations.length === 0) {
            setFormError("沒有任何數量變動。");
            return;
        }

        setFormError(null);
        onSavingChange?.(true);

        try {
            for (const op of pendingOperations) {
                let resolvedBatchId = op.batchId;

                if (op.newBatchDraft) {
                    const createdBatch = await createBatch({
                        variantId: op.variantId,
                        batchNumber: op.newBatchDraft.number,
                        quantity: op.targetQuantity,
                        expiredAt: op.newBatchDraft.expiredAt,
                    });
                    resolvedBatchId = createdBatch.id;
                } else if (resolvedBatchId) {
                    await updateBatch(resolvedBatchId, {
                        quantity: op.targetQuantity,
                    });
                }

                await createInventoryMovement({
                    variantId: op.variantId,
                    batchId: resolvedBatchId,
                    quantityAdjusted: op.delta,
                    locationId,
                    referenceType: "ADJUSTMENT",
                    referenceId: reason.trim() ? reason.trim() : null,
                });
            }

            onSuccess();
        } catch (err: unknown) {
            setFormError(err instanceof Error ? err.message : "庫存調整失敗。");
        } finally {
            onSavingChange?.(false);
        }
    };

    useImperativeHandle(ref, () => ({ submit: handleSave }));

    return (
        <div className="flex flex-col gap-y-5">
            {formError && <div className={ERROR_PANEL}>{formError}</div>}

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>倉庫</label>
                    <input
                        type="text"
                        className={`${CONTROL_INPUT} bg-muted text-muted-foreground cursor-not-allowed`}
                        value={DEFAULT_LOCATION_NAME}
                        disabled
                    />
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>調整日期</label>
                    <Popover open={adjustmentCalendarOpen} onOpenChange={setAdjustmentCalendarOpen}>
                        <PopoverTrigger
                            render={
                                <Button
                                    variant="outline"
                                    className="w-full justify-start text-left font-normal bg-background border border-input text-foreground hover:bg-muted"
                                >
                                    <CalendarIcon className="mr-2 h-4 w-4 text-slate-400" />
                                    {adjustmentDate ? format(adjustmentDate, "yyyy/MM/dd") : <span>選擇日期</span>}
                                </Button>
                            }
                        />
                        <PopoverContent className="w-auto p-0 bg-popover border-border text-popover-foreground" align="start">
                            <Calendar
                                mode="single"
                                selected={adjustmentDate}
                                onSelect={(date) => {
                                    setAdjustmentDate(date);
                                    setAdjustmentCalendarOpen(false);
                                }}
                            />
                        </PopoverContent>
                    </Popover>
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>原因 (選填)</label>
                    <input
                        type="text"
                        className={CONTROL_INPUT}
                        placeholder="例如: 盤點差異、耗損"
                        value={reason}
                        onChange={(e) => setReason(e.target.value)}
                    />
                </div>
            </div>

            <div className="rounded-lg border border-border overflow-hidden">
                <table className="w-full text-left text-sm text-foreground">
                    <thead className="bg-muted text-muted-foreground font-medium text-xs uppercase tracking-wider">
                        <tr>
                            <th className="py-3 px-4 border-b border-border">商品 / 規格</th>
                            <th className="py-3 px-4 border-b border-border min-w-56">指定批次</th>
                            <th className="py-3 px-4 border-b border-border text-right w-28">批次/目前庫存</th>
                            <th className="py-3 px-4 border-b border-border text-right w-36">調整後數量</th>
                            <th className="py-3 px-4 border-b border-border text-right w-24">變動量</th>
                            <th className="py-3 px-4 border-b border-border w-10" />
                        </tr>
                    </thead>
                    <tbody className="font-mono text-xs">
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={6} className="py-8 text-center text-muted-foreground font-sans">
                                    請在下方新增要調整的商品或批次。
                                </td>
                            </tr>
                        ) : (
                            rows.map((row) => {
                                const item = itemMap.get(row.variantId);
                                const isBatchTracked = batchTrackedMap[row.variantId] ?? false;
                                const current = getCurrentStock(row);
                                const effectiveQty = getEffectiveQuantity(row);
                                const delta = deltaFor(row);
                                const variantBatches = batchesByVariant[row.variantId] ?? [];
                                const isInputDisabled = isBatchTracked && !row.batchId;

                                return (
                                    <tr key={row.rowId} className="border-b border-border/40 hover:bg-muted/20">
                                        <td className="py-2.5 px-4 font-sans">
                                            <div className="font-medium text-foreground">
                                                {item?.productName ?? `款式 #${row.variantId}`}
                                            </div>
                                            {item?.configValues && item.configValues.length > 0 && (
                                                <div className="text-xs text-muted-foreground mt-0.5">
                                                    {item.configValues.join(" / ")}
                                                </div>
                                            )}
                                        </td>

                                        {/* Batch Selector */}
                                        <td className="py-2.5 px-4">
                                            {isBatchTracked ? (
                                                <div className="flex flex-col gap-y-1.5">
                                                    <select
                                                        className={`${CONTROL_INPUT} text-xs py-1 h-8`}
                                                        value={row.batchId === "new" ? NEW_BATCH_VALUE : row.batchId ?? ""}
                                                        onChange={(e) => handleBatchChange(row.rowId, e.target.value)}
                                                    >
                                                        <option value="">選擇要調整的批次...</option>
                                                        {variantBatches.map((b) => (
                                                            <option key={b.id} value={b.id}>
                                                                {b.batchNumber} (現有庫存: {b.quantity})
                                                            </option>
                                                        ))}
                                                        <option value={NEW_BATCH_VALUE}>+ 新增全新批次...</option>
                                                    </select>

                                                    {row.batchId === "new" && (
                                                        <div className="flex items-center gap-2 mt-1">
                                                            <input
                                                                type="text"
                                                                placeholder="批次編號"
                                                                className="flex-1 bg-background border border-input rounded px-2 py-1 text-foreground text-xs focus:outline-none"
                                                                value={row.newBatchNumber ?? ""}
                                                                onChange={(e) =>
                                                                    handleNewBatchNumberChange(row.rowId, e.target.value)
                                                                }
                                                            />
                                                            <Popover>
                                                                <PopoverTrigger
                                                                    render={
                                                                        <Button
                                                                            variant="outline"
                                                                            size="sm"
                                                                            className="bg-background border-input text-foreground text-xs px-2 h-7"
                                                                        >
                                                                            <CalendarIcon className="h-3 w-3 mr-1 text-muted-foreground" />
                                                                            {row.expirationDate
                                                                                ? format(row.expirationDate, "yyyy/MM/dd")
                                                                                : "效期"}
                                                                        </Button>
                                                                    }
                                                                />
                                                                <PopoverContent className="w-auto p-0 bg-popover border-border" align="start">
                                                                    <Calendar
                                                                        mode="single"
                                                                        selected={row.expirationDate}
                                                                        onSelect={(date) =>
                                                                            handleExpirationDateChange(row.rowId, date)
                                                                        }
                                                                    />
                                                                </PopoverContent>
                                                            </Popover>
                                                        </div>
                                                    )}
                                                </div>
                                            ) : (
                                                <span className="text-muted-foreground text-xs">— (無批次管理)</span>
                                            )}
                                        </td>

                                        {/* Current Batch Stock Display */}
                                        <td className="py-2.5 px-4 text-right text-muted-foreground">
                                            {isBatchTracked && !row.batchId ? (
                                                <span className="text-muted-foreground/50">請選批次</span>
                                            ) : (
                                                <span className="font-semibold text-foreground">{current}</span>
                                            )}
                                        </td>

                                        {/* InlineInput for Target Quantity */}
                                        <td className="py-2.5 px-4 text-right">
                                            {isInputDisabled ? (
                                                <span className="text-muted-foreground/50 text-right block px-2 py-1">
                                                    —
                                                </span>
                                            ) : (
                                                <InlineInput<number>
                                                    type="number"
                                                    value={effectiveQty}
                                                    onCommit={(newQty) => handleTargetChange(row.rowId, Math.max(0, newQty))}
                                                />
                                            )}
                                        </td>

                                        {/* Delta Display */}
                                        <td
                                            className={`py-2.5 px-4 text-right font-medium ${delta === null || delta === 0
                                                    ? "text-muted-foreground"
                                                    : delta > 0
                                                        ? "text-emerald-400"
                                                        : "text-amber-400"
                                                }`}
                                        >
                                            {delta === null ? "—" : delta > 0 ? `+${delta}` : delta}
                                        </td>

                                        {/* Remove Row Button */}
                                        <td className="py-2.5 px-4 text-right">
                                            <button
                                                type="button"
                                                onClick={() => handleRemoveRow(row.rowId)}
                                                className="text-muted-foreground hover:text-destructive p-1 transition-colors"
                                                title="移除"
                                            >
                                                <X className="w-4 h-4" />
                                            </button>
                                        </td>
                                    </tr>
                                );
                            })
                        )}
                    </tbody>
                </table>
            </div>

            {/* Add Product Line (Multi-Add Enabled) */}
            <div className="flex flex-col gap-y-1">
                <label className={FIELD_LABEL}>新增調整品項</label>
                <div className="flex gap-2">
                    <select
                        className={CONTROL_INPUT}
                        value=""
                        onChange={(e) => {
                            if (e.target.value) handleAddRow(Number(e.target.value));
                        }}
                    >
                        <option value="">選擇要調整的商品或規格 (可重複新增)...</option>
                        {selectableVariants.map((variant) => (
                            <option key={variant.variantId} value={variant.variantId}>
                                {variant.label}
                            </option>
                        ))}
                    </select>
                </div>
            </div>
        </div>
    );
};