import { useImperativeHandle, useMemo, useState, useCallback } from "react";
import { X, Calendar as CalendarIcon } from "lucide-react";
import { CONTROL_INPUT, ERROR_PANEL, FIELD_LABEL } from "@/lib/styles";
import { useInventoryCatalog, useProductCatalog, useVariant } from "@/hooks/useContexts";
import type {
    KatanaBatch,
    KatanaInventoryItem,
    KatanaStockAdjustmentRowInput,
    KatanaTraceabilityEntry,
} from "@my-inventory-app/shared";

import { Calendar } from "@/components/ui/calendar";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { addYears, format, subDays } from "date-fns";

const NEW_BATCH_VALUE = "__new__";
const DEFAULT_LOCATION_ID = 1;
const DEFAULT_LOCATION_NAME = "晁欣";

export interface StockAdjustmentHandle {
    submit: () => Promise<void>;
}

interface StockAdjustmentProps {
    items: KatanaInventoryItem[];
    initialVariantId?: number | null;
    onSavingChange?: (isSaving: boolean) => void;
    onSuccess: () => void;
    ref?: React.Ref<StockAdjustmentHandle>;
}

interface AdjustmentDraftRow {
    variantId: number;
    targetQuantity?: string;
    batchId?: number | "new";
    newBatchNumber?: string;
    batchNameAutoGenerated?: boolean;
    expirationDate?: Date;
}

const roundQuantity = (value: number): number => Math.round(value * 1e6) / 1e6;
const getDefaultBatchNumber = (expirationDate?: Date): string =>
    `${format(new Date(), "yyyy/MM/dd")} - ${expirationDate ? format(expirationDate, "yyyy/MM/dd") : "未設定"}`;
const getDefaultBatchExpirationDate = (): Date =>
    subDays(addYears(new Date(), 2), 1);

export const StockAdjustment = ({
    items,
    initialVariantId,
    onSavingChange,
    onSuccess,
    ref,
}: StockAdjustmentProps) => {
    const { products } = useProductCatalog();
    const { variants } = useVariant();
    const { batches, createBatch, createStockAdjustment } = useInventoryCatalog();

    const [locationId] = useState<number>(DEFAULT_LOCATION_ID);
    const [rows, setRows] = useState<AdjustmentDraftRow[]>(() =>
        initialVariantId != null
            ? [{ variantId: initialVariantId, targetQuantity: undefined }]
            : []
    );
    const [reason, setReason] = useState("");
    const [adjustmentDate, setAdjustmentDate] = useState<Date | undefined>(() => new Date());
    const [adjustmentCalendarOpen, setAdjustmentCalendarOpen] = useState(false);
    const [formError, setFormError] = useState<string | null>(null);

    const getVariantMetadata = useCallback(
        (variantId: number) => {
            const variant = variants.get(variantId);
            const product = variant ? products.get(variant.product_id) : undefined;
            const detailsString = variant?.config_attributes
                ?.map((attr) => attr.config_value)
                .filter(Boolean)
                .join(" / ");

            return {
                product,
                variant,
                product_name: product?.name ?? `Variant #${variantId}`,
                variant_details: detailsString || undefined,
                is_batch_tracked: product?.batch_tracked ?? false,
            };
        },
        [products, variants]
    );

    const stockByVariant = useMemo(() => {
        const byVariant = new Map<number, number>();
        for (const item of items) {
            // Fall back to matching all items if location_id doesn't strictly match
            if (locationId != null && item.location_id != null && item.location_id !== locationId) continue;
            byVariant.set(item.variant_id, Number(item.quantity_in_stock) || 0);
        }
        return byVariant;
    }, [items, locationId]);;

    const batchesByVariant = useMemo(() => {
        const byVariant = new Map<number, KatanaBatch[]>();
        for (const b of batches.values()) {
            const list = byVariant.get(b.variant_id) ?? [];
            list.push(b);
            byVariant.set(b.variant_id, list);
        }
        return byVariant;
    }, [batches]);

    const selectableVariants = useMemo(() => {
        const alreadyAdded = new Set(rows.map((row) => row.variantId));

        return items
            .filter((item) => !alreadyAdded.has(item.variant_id)) // <-- Don't choke if item.location_id is missing or different
            .map((item) => {
                const meta = getVariantMetadata(item.variant_id);
                return {
                    variantId: item.variant_id,
                    label: meta.variant_details
                        ? `${meta.product_name} - ${meta.variant_details}`
                        : meta.product_name,
                };
            })
            .sort((a, b) => a.label.localeCompare(b.label));
    }, [items, rows, getVariantMetadata]);

    const handleAddRow = (variantId: number) => {
        setFormError(null);
        setRows((prev) => [...prev, { variantId, targetQuantity: undefined }]);
    };

    const handleRemoveRow = (variantId: number) => {
        setRows((prev) => prev.filter((row) => row.variantId !== variantId));
    };

    const handleTargetChange = (variantId: number, targetQuantity: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => (row.variantId === variantId ? { ...row, targetQuantity } : row))
        );
    };

    const handleBatchChange = (variantId: number, value: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.variantId !== variantId) return row;

                if (value === "") {
                    return {
                        ...row,
                        batchId: undefined,
                        newBatchNumber: undefined,
                        batchNameAutoGenerated: undefined,
                        expirationDate: undefined,
                    };
                }
                if (value === NEW_BATCH_VALUE) {
                    return {
                        ...row,
                        batchId: "new",
                        expirationDate: getDefaultBatchExpirationDate(),
                        newBatchNumber: getDefaultBatchNumber(getDefaultBatchExpirationDate()),
                        batchNameAutoGenerated: true,
                    };
                }
                return {
                    ...row,
                    batchId: Number(value),
                    newBatchNumber: undefined,
                    batchNameAutoGenerated: undefined,
                    expirationDate: undefined,
                };
            })
        );
    };

    const handleNewBatchNumberChange = (variantId: number, newBatchNumber: string) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) =>
                row.variantId === variantId
                    ? { ...row, newBatchNumber, batchNameAutoGenerated: false }
                    : row
            )
        );
    };

    const handleAdjustmentDateSelect = (date: Date | undefined) => {
        setAdjustmentDate(date);
        setAdjustmentCalendarOpen(false);
    };

    const handleExpirationDateChange = (variantId: number, date: Date | undefined) => {
        setFormError(null);
        setRows((prev) =>
            prev.map((row) => {
                if (row.variantId !== variantId) return row;
                return {
                    ...row,
                    expirationDate: date,
                    ...(row.batchNameAutoGenerated && {
                        newBatchNumber: getDefaultBatchNumber(date),
                    }),
                };
            })
        );
    };

    const getEffectiveQuantityString = (row: AdjustmentDraftRow): string => {
        if (row.targetQuantity !== undefined) return row.targetQuantity;
        return String(stockByVariant.get(row.variantId) ?? 0);
    };

    const deltaFor = (row: AdjustmentDraftRow): number | null => {
        const rawStr = getEffectiveQuantityString(row);
        if (rawStr.trim() === "") return null;

        const target = Number(rawStr);
        if (Number.isNaN(target)) return null;

        return roundQuantity(target - (stockByVariant.get(row.variantId) ?? 0));
    };

    const handleSave = async () => {
        const adjustmentRows: KatanaStockAdjustmentRowInput[] = [];

        for (const row of rows) {
            const rawStr = getEffectiveQuantityString(row);
            if (rawStr.trim() === "") continue;

            const target = Number(rawStr);
            if (Number.isNaN(target)) {
                setFormError("調整後數量必須是數字。");
                return;
            }
            if (target < 0) {
                setFormError("調整後數量不可小於 0。");
                return;
            }

            const delta = roundQuantity(target - (stockByVariant.get(row.variantId) ?? 0));
            if (delta === 0) continue;

            let traceability: KatanaTraceabilityEntry[] | undefined;
            const meta = getVariantMetadata(row.variantId);

            if (meta.is_batch_tracked && row.batchId !== undefined) {
                let resolvedBatchId: number;

                if (row.batchId === "new") {
                    const trimmed = row.newBatchNumber?.trim();
                    if (!trimmed) {
                        setFormError("請輸入新批次編號。");
                        return;
                    }
                    try {
                        const created = await createBatch({
                            batch_number: trimmed,
                            variant_id: row.variantId,
                            batch_created_date: format(new Date(), "yyyy-MM-dd"),
                            expiration_date: row.expirationDate ? row.expirationDate.toISOString() : undefined,
                        });
                        resolvedBatchId = created.id;
                    } catch (err: unknown) {
                        setFormError(err instanceof Error ? err.message : "建立批次失敗。");
                        return;
                    }
                } else {
                    resolvedBatchId = row.batchId;
                }

                traceability = [{ batch_id: resolvedBatchId, quantity: String(delta) }];
            }

            adjustmentRows.push({
                variant_id: row.variantId,
                quantity: delta,
                ...(traceability && { traceability }),
            });
        }

        if (adjustmentRows.length === 0) {
            setFormError("沒有任何數量變動。");
            return;
        }

        setFormError(null);
        onSavingChange?.(true);

        try {
            const data = await createStockAdjustment({
                location_id: locationId,
                stock_adjustment_date: adjustmentDate ? adjustmentDate.toISOString() : undefined,
                reason,
                stock_adjustment_rows: adjustmentRows,
            });

            if (data) {
                onSuccess();
            } else {
                setFormError("庫存調整失敗。");
            }
        } catch (err: unknown) {
            setFormError(err instanceof Error ? err.message : "庫存調整失敗。");
        } finally {
            onSavingChange?.(false);
        }
    };

    useImperativeHandle(ref, () => ({ submit: handleSave }));

    return (
        <div className="flex flex-col gap-y-5">
            {formError && <div className={ERROR_PANEL}>{formError}</div>}

            <div className="grid grid-cols-3 gap-4">
                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>倉庫</label>
                    <input
                        type="text"
                        className={`${CONTROL_INPUT} bg-muted text-muted-foreground cursor-not-allowed`}
                        value={DEFAULT_LOCATION_NAME}
                        disabled
                    />
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>調整日期</label>
                    <Popover open={adjustmentCalendarOpen} onOpenChange={setAdjustmentCalendarOpen}>
                        <PopoverTrigger
                            render={
                                <Button
                                    variant="outline"
                                    className="w-full justify-start text-left font-normal bg-background border border-input text-foreground hover:bg-muted"
                                >
                                    <CalendarIcon className="mr-2 h-4 w-4 text-slate-400" />
                                    {adjustmentDate ? format(adjustmentDate, "yyyy/MM/dd") : <span>選擇日期</span>}
                                </Button>
                            }
                        />
                        <PopoverContent className="w-auto p-0 bg-popover border-border text-popover-foreground" align="start">
                            <Calendar
                                mode="single"
                                selected={adjustmentDate}
                                onSelect={handleAdjustmentDateSelect}
                            />
                        </PopoverContent>
                    </Popover>
                </div>

                <div className="flex flex-col gap-y-1">
                    <label className={FIELD_LABEL}>原因 (選填)</label>
                    <input
                        type="text"
                        className={CONTROL_INPUT}
                        placeholder="例如: 盤點差異、耗損"
                        value={reason}
                        onChange={(e) => setReason(e.target.value)}
                    />
                </div>
            </div>

            <div className="rounded-lg border border-slate-800 overflow-hidden">
                <table className="w-full text-left text-sm text-slate-300">
                    <thead className="bg-slate-950 text-slate-400 font-medium text-xs uppercase tracking-wider">
                        <tr>
                            <th className="py-3 px-4 border-b border-slate-800">商品 / 規格</th>
                            <th className="py-3 px-4 border-b border-slate-800 text-right">目前庫存</th>
                            <th className="py-3 px-4 border-b border-slate-800 text-right">調整後數量</th>
                            <th className="py-3 px-4 border-b border-slate-800">批次與有效日期</th>
                            <th className="py-3 px-4 border-b border-slate-800 text-right">變動</th>
                            <th className="py-3 px-4 border-b border-slate-800 w-10" />
                        </tr>
                    </thead>
                    <tbody className="font-mono text-xs">
                        {rows.length === 0 ? (
                            <tr>
                                <td colSpan={6} className="py-8 text-center text-slate-500 font-sans">
                                    請在下方新增要調整的商品。
                                </td>
                            </tr>
                        ) : (
                            rows.map((row) => {
                                const meta = getVariantMetadata(row.variantId);
                                const current = stockByVariant.get(row.variantId) ?? 0;
                                const effectiveQtyStr = getEffectiveQuantityString(row);
                                const delta = deltaFor(row);
                                const variantBatches = batchesByVariant.get(row.variantId) ?? [];

                                return (
                                    <tr key={row.variantId} className="border-b border-slate-800/40">
                                        <td className="py-2.5 px-4 font-sans">
                                            <div className="font-medium text-slate-100">
                                                {meta.product_name}
                                            </div>
                                            {meta.variant_details && (
                                                <div className="text-xs text-muted-foreground mt-0.5">
                                                    {meta.variant_details}
                                                </div>
                                            )}
                                        </td>
                                        <td className="py-2.5 px-4 text-right text-slate-400">
                                            {current}
                                        </td>
                                        <td className="py-2.5 px-4 text-right">
                                            <input
                                                type="number"
                                                step="any"
                                                min="0"
                                                className="w-28 text-right bg-slate-900 border border-slate-700 focus:border-emerald-500 rounded px-2 py-1 text-slate-100 focus:outline-none transition"
                                                value={effectiveQtyStr}
                                                onChange={(e) =>
                                                    handleTargetChange(row.variantId, e.target.value)
                                                }
                                            />
                                        </td>
                                        <td className="py-2.5 px-4 gap-x-3">
                                            {meta.is_batch_tracked ? (
                                                <div className="flex gap-x-3 items-center w-full">
                                                    <div className="flex flex-col gap-y-1 w-full">
                                                        <select
                                                            className="bg-background border border-input focus:border-ring rounded px-2 py-1 text-foreground focus:outline-none focus:ring-2 focus:ring-ring/30 transition"
                                                            value={
                                                                row.batchId === "new"
                                                                    ? NEW_BATCH_VALUE
                                                                    : row.batchId ?? ""
                                                            }
                                                            onChange={(e) =>
                                                                handleBatchChange(row.variantId, e.target.value)
                                                            }
                                                        >
                                                            <option value="">選擇批次...</option>
                                                            {variantBatches
                                                                .filter((b) => b.batch_number !== "Unbatched")
                                                                .map((b) => (
                                                                    <option key={b.id} value={b.id}>
                                                                        {b.batch_number}
                                                                    </option>
                                                                ))}
                                                            <option value={NEW_BATCH_VALUE}>+ 新增批次...</option>
                                                        </select>
                                                        {row.batchId === "new" && (
                                                            <input
                                                                type="text"
                                                                placeholder="新批次編號"
                                                                className="bg-background border border-input focus:border-ring rounded px-2 py-1 text-foreground focus:outline-none focus:ring-2 focus:ring-ring/30 transition"
                                                                value={row.newBatchNumber ?? ""}
                                                                onChange={(e) =>
                                                                    handleNewBatchNumberChange(
                                                                        row.variantId,
                                                                        e.target.value
                                                                    )
                                                                }
                                                            />
                                                        )}
                                                    </div>

                                                    {row.batchId === "new" && (
                                                        <div>
                                                            <Popover>
                                                                <PopoverTrigger
                                                                    render={
                                                                        <Button
                                                                            variant="outline"
                                                                            size="sm"
                                                                            className="bg-slate-900 border-slate-700 text-slate-200 hover:bg-slate-800 text-xs px-2.5"
                                                                        >
                                                                            <CalendarIcon className="h-3.5 w-3.5 mr-1 text-slate-400" />
                                                                            {row.expirationDate
                                                                                ? format(row.expirationDate, "yyyy/MM/dd")
                                                                                : "有效日期"}
                                                                        </Button>
                                                                    }
                                                                />
                                                                <PopoverContent className="w-auto p-0 bg-popover border-border text-popover-foreground" align="start">
                                                                    <Calendar
                                                                        mode="single"
                                                                        selected={row.expirationDate}
                                                                        onSelect={(date) => handleExpirationDateChange(row.variantId, date)}
                                                                    />
                                                                </PopoverContent>
                                                            </Popover>
                                                        </div>
                                                    )}
                                                </div>
                                            ) : (
                                                <span className="text-slate-600">—</span>
                                            )}
                                        </td>
                                        <td
                                            className={`py-2.5 px-4 text-right font-medium ${delta === null || delta === 0
                                                ? "text-slate-500"
                                                : delta > 0
                                                    ? "text-emerald-400"
                                                    : "text-amber-400"
                                                }`}
                                        >
                                            {delta === null ? "—" : delta > 0 ? `+${delta}` : delta}
                                        </td>
                                        <td className="py-2.5 px-4 text-right">
                                            <button
                                                type="button"
                                                onClick={() => handleRemoveRow(row.variantId)}
                                                className="text-slate-500 hover:text-red-400 p-1"
                                                title="移除"
                                            >
                                                <X className="w-4 h-4" />
                                            </button>
                                        </td>
                                    </tr>
                                );
                            })
                        )}
                    </tbody>
                </table>
            </div>

            <div className="flex flex-col gap-y-1">
                <label className={FIELD_LABEL}>新增商品</label>
                <select
                    className={CONTROL_INPUT}
                    value=""
                    onChange={(e) => {
                        if (e.target.value) handleAddRow(Number(e.target.value));
                    }}
                >
                    <option value="">選擇要調整的商品...</option>
                    {selectableVariants.map((variant) => (
                        <option key={variant.variantId} value={variant.variantId}>
                            {variant.label}
                        </option>
                    ))}
                </select>
            </div>
        </div>
    );
};