ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_adjustment_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_adjustment_traceability ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_order_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_order_shipping_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_order_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE manufacturing_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_rows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public full access" ON addresses FOR ALL USING (true);
CREATE POLICY "Public full access" ON locations FOR ALL USING (true);
CREATE POLICY "Public full access" ON products FOR ALL USING (true);
CREATE POLICY "Public full access" ON product_configs FOR ALL USING (true);
CREATE POLICY "Public full access" ON product_variants FOR ALL USING (true);
CREATE POLICY "Public full access" ON inventory_levels FOR ALL USING (true);
CREATE POLICY "Public full access" ON batches FOR ALL USING (true);
CREATE POLICY "Public full access" ON stock_adjustments FOR ALL USING (true);
CREATE POLICY "Public full access" ON stock_adjustment_rows FOR ALL USING (true);
CREATE POLICY "Public full access" ON stock_adjustment_traceability FOR ALL USING (true);
CREATE POLICY "Public full access" ON customers FOR ALL USING (true);
CREATE POLICY "Public full access" ON customer_addresses FOR ALL USING (true);
CREATE POLICY "Public full access" ON sales_orders FOR ALL USING (true);
CREATE POLICY "Public full access" ON sales_order_addresses FOR ALL USING (true);
CREATE POLICY "Public full access" ON sales_order_shipping_fees FOR ALL USING (true);
CREATE POLICY "Public full access" ON sales_order_rows FOR ALL USING (true);
CREATE POLICY "Public full access" ON manufacturing_orders FOR ALL USING (true);
CREATE POLICY "Public full access" ON purchase_orders FOR ALL USING (true);
CREATE POLICY "Public full access" ON purchase_order_rows FOR ALL USING (true);