CREATE TABLE sales_orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE RESTRICT NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT NOT NULL,
  source TEXT,
  status katana_sales_order_status DEFAULT 'NOT_SHIPPED' NOT NULL,
  order_created_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  delivery_date TIMESTAMPTZ,
  picked_date TIMESTAMPTZ,
  invoicing_status TEXT,
  customer_ref TEXT,
  currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
  conversion_rate NUMERIC(12, 6) DEFAULT 1.0,
  conversion_date TIMESTAMPTZ,
  total NUMERIC(14, 4) DEFAULT 0.0000 NOT NULL,
  total_in_base_currency NUMERIC(14, 4) DEFAULT 0.0000 NOT NULL,
  product_availability katana_product_availability DEFAULT 'NOT_AVAILABLE',
  product_expected_date TIMESTAMPTZ,
  ingredient_availability katana_ingredient_availability DEFAULT 'NOT_APPLICABLE',
  ingredient_expected_date TIMESTAMPTZ,
  production_status katana_production_status DEFAULT 'NONE',
  additional_info TEXT,
  ecommerce_order_type TEXT,
  ecommerce_store_name TEXT,
  ecommerce_order_id TEXT,
  tracking_number TEXT,
  tracking_number_url TEXT,
  custom_fields JSONB DEFAULT '{}'::JSONB,
  billing_address_id BIGINT,
  shipping_address_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE TABLE sales_order_addresses (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sales_order_id BIGINT REFERENCES sales_orders(id) ON DELETE CASCADE NOT NULL,
  entity_type TEXT CHECK (entity_type IN ('billing', 'shipping')) NOT NULL,
  first_name TEXT,
  last_name TEXT,
  company TEXT,
  phone TEXT,
  line_1 TEXT NOT NULL,
  line_2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip TEXT NOT NULL,
  country TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE sales_order_shipping_fees (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sales_order_id BIGINT REFERENCES sales_orders(id) ON DELETE CASCADE NOT NULL UNIQUE,
  description TEXT,
  amount NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
  tax_rate_id BIGINT
);

CREATE TABLE sales_order_rows (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sales_order_id BIGINT REFERENCES sales_orders(id) ON DELETE CASCADE NOT NULL,
  variant_id BIGINT REFERENCES product_variants(id) ON DELETE RESTRICT NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT,
  quantity NUMERIC(12, 4) NOT NULL,
  price_per_unit NUMERIC(12, 4) NOT NULL,
  price_per_unit_in_base_currency NUMERIC(12, 4),
  tax_rate_id BIGINT,
  tax_rate NUMERIC(5, 2) DEFAULT 0.00,
  total NUMERIC(14, 4) GENERATED ALWAYS AS (quantity * price_per_unit) STORED,
  total_in_base_currency NUMERIC(14, 4),
  cogs_value NUMERIC(14, 4),
  product_availability katana_product_availability DEFAULT 'NOT_AVAILABLE',
  product_expected_date TIMESTAMPTZ,
  linked_manufacturing_order_id BIGINT,
  conversion_rate NUMERIC(12, 6) DEFAULT 1.0,
  conversion_date TIMESTAMPTZ,
  attributes JSONB DEFAULT '[]'::JSONB,
  traceability JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  deleted_at TIMESTAMPTZ
);