CREATE TABLE manufacturing_orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  status katana_mo_status DEFAULT 'NOT_STARTED' NOT NULL,
  order_no TEXT NOT NULL UNIQUE,
  variant_id BIGINT REFERENCES product_variants(id) ON DELETE RESTRICT NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT NOT NULL,
  planned_quantity NUMERIC(12, 4) NOT NULL,
  actual_quantity NUMERIC(12, 4),
  order_created_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  done_date TIMESTAMPTZ,
  production_deadline_date TIMESTAMPTZ,
  additional_info TEXT,
  is_linked_to_sales_order BOOLEAN DEFAULT FALSE NOT NULL,
  sales_order_id BIGINT REFERENCES sales_orders(id) ON DELETE SET NULL,
  sales_order_row_id BIGINT REFERENCES sales_order_rows(id) ON DELETE SET NULL,
  sales_order_delivery_deadline TIMESTAMPTZ,
  ingredient_availability katana_ingredient_availability DEFAULT 'NO_RECIPE',
  total_cost NUMERIC(14, 4) DEFAULT 0.0000,
  total_planned_time INTEGER,
  total_actual_time INTEGER,
  material_cost NUMERIC(14, 4) DEFAULT 0.0000,
  subassemblies_cost NUMERIC(14, 4) DEFAULT 0.0000,
  operations_cost NUMERIC(14, 4) DEFAULT 0.0000,
  traceability JSONB DEFAULT '[]'::JSONB,
  serial_numbers JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  deleted_at TIMESTAMPTZ
);