CREATE TABLE purchase_orders (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL UNIQUE,
  supplier_id BIGINT NOT NULL,
  status katana_po_status DEFAULT 'NOT_RECEIVED' NOT NULL,
  location_id BIGINT REFERENCES locations(id) ON DELETE RESTRICT NOT NULL,
  expected_arrival_date TIMESTAMPTZ,
  currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE purchase_order_rows (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT REFERENCES purchase_orders(id) ON DELETE CASCADE NOT NULL,
  variant_id BIGINT REFERENCES product_variants(id) ON DELETE RESTRICT NOT NULL,
  quantity NUMERIC(12, 4) NOT NULL,
  price_per_unit NUMERIC(12, 4) NOT NULL,
  received_quantity NUMERIC(12, 4) DEFAULT 0.0000 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);